replicaCount: 1

image:
  repository: artifactory.pele.local/pele-dockers/devops/base/slurm
  tag: "23.02.5" # Set slurmrestd version to enable paradise to use old v0.0.37 (temporary).
  pullPolicy: Always

hostname: slurmrestd

init_node:
  securityContext: {}

munged:
  securityContext:
    runAsUser: 511
  resources: {}

securityContext: {}
resources: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  ports:
    - name: slurmrestd-tcp
      protocol: TCP
      port: 6820
      targetPort: 6820

podAnnotations: {}

podSecurityContext: {}
  # runAsUser: 1000
  # fsGroup: 2000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
