apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-slurm-cluster-munge-key
  labels:
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  munge.key: |-
    {{ .Files.Get "files/munge.key" | b64enc }}
