replicaCount: 1

image:
  repository: artifactory.pele.local/pele-dockers/devops/base/slurm
  tag: "0.0.0" # Forcing the developer to set value when deploying new release
  pullPolicy: Always

hostname: slurmctld

storage:
  spool:
    name: slurm-controller-spool
    storageClass: trident-iscsi-csi
    size: 50Gi

init_node:
  securityContext: {}

munged:
  securityContext:
    runAsUser: 511
  resources: {}

securityContext: {}
resources: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  ports:
    - name: slurmctld-tcp
      protocol: TCP
      port: 6817
      targetPort: 6817

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

networkSettings: {}
